### ISSUE TITLE
Tagging & releases

### ISSUE THREAD

**Issue by 0mp** [csjayp/setaudit#6]
It would be easier to port if we start tagging releases. What do you think, @csjayp ?

**Comment by csjayp** [comment]
Sounds good to me. I can create a tag once we update the man page

**Comment by 0mp** [comment]
Alright, the man page has been updated.

**Comment by csjayp** [comment]
v1.0.0 has been tagged, thanks for your help on this!

**Comment by 0mp** [comment]
Cool, the port submission has just been updated BTW.
